Edits to model after review
LM1398/pfs pull request #20
Opened 2021-09-06 05:51 UTC by LM1398

2021-09-06 23:13 UTC, atsushimemet commented
@LM1398 
notification testです。

2021-09-06 23:28 UTC, atsushimemet requested changes
@LM1398 
一部修正して下さい。

2021-09-06 23:28 UTC, atsushimemet commented on source_directory/model1_pfs_preprocessing.py
> +    trans = json.load("~/samurai/pfs/data_directory/input/big_category_rus_eng.json")
@LM1398 
ディレクトリ名が変更になっているので、修正しておきましょう。

2021-09-06 23:28 UTC, atsushimemet commented on source_directory/model1_pfs_preprocessing.py
> +
@LM1398 
ここの空白行はいらないと思います。Blackはどのように反応しますか?

2021-09-06 23:28 UTC, atsushimemet commented on source_directory/model1_pfs_preprocessing.py
> +    Also fixes one of the typos in the shop names.
素晴らしいDocstringです。

2021-09-07 00:26 UTC, LM1398 commented on source_directory/model1_pfs_preprocessing.py
> +    trans = json.load("~/samurai/pfs/data_directory/input/big_category_rus_eng.json")
これjupyterで試したらエラーが出たので、コード自体も修正しました！

2021-09-07 00:29 UTC, LM1398 commented on source_directory/model1_pfs_preprocessing.py
> +
Formatting with blackと出てきてたのですが、formatしてませんでした。色々調べてたところ、
`df.columns = (
        ["date_block_num", "shop_id", "item_id", "item_category_id", "big_category", "city"]
        + ["_".join(["item_cnt_month", str(block) for block in range(len(34))])])`
このコードでエラーが出ていたせいでblack先生がformat出来なかったようです。なのでとりあえず前のコードを代用したらblack先生復活しました。ですが、docstringの下の空行は直さなかったので自分でやりました！

2021-09-07 00:29 UTC, LM1398 commented on source_directory/model1_pfs_preprocessing.py
> +    Also fixes one of the typos in the shop names.
ありがとうございます！

2021-09-07 09:53 UTC, atsushimemet commented on source_directory/model1_pfs_preprocessing.py
> +    trans = json.load("~/samurai/pfs/data_directory/input/big_category_rus_eng.json")
@LM1398 
"~/samurai/pfs/data_directory/input/big_category_rus_eng.json"を
"~/samurai/pfs/data/input/big_category_rus_eng.json"
のように変更して欲しかったのですが、エラー出ましたか?

2021-09-07 09:55 UTC, atsushimemet commented on source_directory/model1_pfs_preprocessing.py
> +    trans = json.load("~/samurai/pfs/data_directory/input/big_category_rus_eng.json")
@LM1398 
もし、このブランチでは、
```
pfs/data/input/big_category_rus_eng.json
```
が存在しないようであれば、一旦、
```
~/samurai/pfs/data/input/big_category_rus_eng.json
```
に変更してもらって、エラーが出たままでも構いません。

2021-09-07 10:21 UTC, LM1398 commented on source_directory/model1_pfs_preprocessing.py
> +    trans = json.load("~/samurai/pfs/data_directory/input/big_category_rus_eng.json")
すいません！これはjson.loadに問題があってので、ついでにコードを書き換えた感じです。pathは変えて問題なかったです！

2021-09-07 11:00 UTC, atsushimemet requested changes

2021-09-07 11:00 UTC, atsushimemet commented on source_directory/model1_pfs_preprocessing.py
> +    }
@LM1398 
この辞書は長すぎます。
内包表記などを使用して、短く簡潔に書いて下さい。
わからなければ、質問して下さい。

2021-09-07 11:13 UTC, LM1398 commented on source_directory/model1_pfs_preprocessing.py
> +    }
直しました！

2021-09-07 11:52 UTC, atsushimemet requested changes
@LM1398 
gitignoreの変更を除外して下さい。よろしくお願い致します。

2021-09-07 11:52 UTC, atsushimemet commented on .gitignore
> +.DS_Store
@LM1398 
.gitignoreの変更は、別のブランチで行って下さい。

2021-09-07 11:52 UTC, atsushimemet commented on source_directory/model1_pfs_preprocessing.py
> +    ] + ["item_cnt_month_" + str(x) for x in range(0, 34)]
素晴らしいです。

2021-09-07 12:30 UTC, LM1398 commented on source_directory/model1_pfs_preprocessing.py
> +    ] + ["item_cnt_month_" + str(x) for x in range(0, 34)]
ありがとうございます！

2021-09-07 12:36 UTC, LM1398 commented on .gitignore
> +.DS_Store
直そうとしている間にミスをしたので新しいブランチを作りました。すいません

2021-09-07 23:27 UTC, atsushimemet approved these changes

2021-09-07 23:28 UTC, atsushimemet commented
@LM1398 
git本当に上達しましたね。松村さんを指導させてもらっている最中、たまに泣きそうになります 笑
では、pfsのスコア提出どんどん進めていきましょう!!!

2021-09-07 23:28 UTC, merged